[project]
name = "phi-automata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=4.2.0",
    "dash-iconify>=0.1.2",
    "dash-mantine-components>=2.7.0",
    "matplotlib>=3.10.9",
    "notebook>=7.5.7",
    "numpy>=2.4.6",
    "plotly>=6.8.0",
]
