import dash_mantine_components as dmc
from dash_iconify import DashIconify

from app.widgets.metrics_card import Metric, create_metrics_card


# --------------------
# HEADER
# --------------------

def get_title():
    return dmc.Text(
        "Metrics Panel",
        size='lg',
        fw=500,
    )


def get_collapse_button():
    return dmc.ActionIcon(
        DashIconify(
            icon='ri:arrow-right-double-fill',
            width=24,
        ),
        id='collapse-metrics-panel-button',
        variant='subtle',
        size='md',
    )


def get_metrics_panel_header():
    return dmc.Group(
        [
            get_title(),
            get_collapse_button(),
        ],
        gap=4,
        align='center',
        justify='space-between'
    )


# --------------------
# COMPLEXITY METRICS
# --------------------

def get_complexity_metrics():
    return create_metrics_card(
        section_title='Complexity',
        metrics=[
            Metric(
                name='lambda',
                label="λ",
                info_tooltip="Fraction of neighborhood configurations that produce an active state. "
                             "Measures the rule's tendency toward activity and complexity.",
            ),
            Metric(
                name='entropy',
                label="Entropy",
                info_tooltip="Shannon entropy of the automaton states. "
                             "Measures randomness and information content.",
            ),
            Metric(
                name='compression-complexity',
                label="Compression Complexity",
                info_tooltip="Complexity estimated from compressibility. "
                             "Less compressible patterns are considered more complex.",
            ),
        ]
    )


# --------------------
# DYNAMICS METRICS
# --------------------

def get_dynamics_metrics():
    return create_metrics_card(
        section_title='Dynamics',
        metrics=[
            Metric(
                name='damage-spread',
                label="Damage Spread",
                info_tooltip="Measures how strongly a small perturbation "
                             "propagates through the system over time.",
            ),
            Metric(
                name='active-density',
                label="Active Density",
                info_tooltip="Fraction of active cells across the automaton evolution. "
                             "Indicates overall activity level.",
            ),
            Metric(
                name='sensitivity',
                label="Sensitivity",
                info_tooltip="Measures how responsive the automaton is "
                             "to changes in initial conditions.",
            ),
        ]
    )


# --------------------
# INFORMATION METRICS
# --------------------

def get_information_metrics():
    return create_metrics_card(
        section_title='Information',
        metrics=[
            Metric(
                name='excess-information',
                label="Excess Information",
                info_tooltip="Information generated by the system beyond what "
                             "is explained by its individual components.",
            ),
            Metric(
                name='phi',
                label="Φ",
                info_tooltip="Integrated Information. Measures the extent to "
                             "which information is unified across the system.",
            ),
        ]
    )


# --------------------
# CLASSIFICATION METRICS
# --------------------

def get_classification_metrics():
    return create_metrics_card(
        section_title='Classification',
        metrics=[
            Metric(
                name='wolfram-class',
                label="Wolfram Class",
                info_tooltip="Behavioral classification of the rule "
                             "according to Wolfram's four classes.",
            ),
            Metric(
                name='criticality',
                label="Criticality",
                info_tooltip="Indicates whether the system operates in "
                             "an ordered, chaotic, or critical regime.",
            ),
        ]
    )


# --------------------
# METRICS PANEL
# --------------------

def create_metrics_panel():
    return dmc.Paper(
        dmc.Stack(
            [
                get_metrics_panel_header(),
                get_complexity_metrics(),
                get_dynamics_metrics(),
                get_information_metrics(),
                get_classification_metrics(),
            ],
        ),
        withBorder=True,
        p='md',
        radius=0,
        shadow='xs',
        w=350,
    )